// mobile/pages/system/role-form/role-form.vue
<template>
  <view class="page page-container">
    <u-loading-page :loading="loading" loading-text="加载中..." />

    <view v-if="!loading" class="card">
      <u-form label-position="top">
        <u-form-item label="角色编码" required>
          <u-input
            v-model="form.roleCode"
            placeholder="如 admin"
            :disabled="isEdit"
            clearable />
        </u-form-item>
        <u-form-item label="角色名称" required>
          <u-input v-model="form.roleName" placeholder="如 管理员" clearable />
        </u-form-item>
        <u-form-item label="描述">
          <u-textarea v-model="form.description" placeholder="可选" count maxlength="200" />
        </u-form-item>
        <u-form-item v-if="isEdit" label="启用">
          <u-switch v-model="form.isActive" />
        </u-form-item>
      </u-form>
    </view>

    <view class="actions">
      <u-button type="primary" :loading="saving" text="保存" @click="submit" />
      <u-button text="取消" custom-style="margin-top: 20rpx;" @click="goBack" />
    </view>
  </view>
</template>

<script setup>
import { reactive, ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import * as roleService from '@/service/role.service';
import { useUserStore } from '@/store/user';

const userStore = useUserStore();

const isEdit = ref(false);
const roleId = ref(null);
const loading = ref(false);
const saving = ref(false);

const form = reactive({
  roleCode: '',
  roleName: '',
  description: '',
  isActive: true
});

onLoad(options => {
  if (!userStore.isLoggedIn) {
    uni.reLaunch({ url: '/pages/login/login' });
    return;
  }

  if (options.id) {
    isEdit.value = true;
    roleId.value = Number(options.id);
    if (!userStore.hasPermission('system.roles:edit')) {
      uni.showToast({ title: '无权编辑角色', icon: 'none' });
      setTimeout(goBack, 500);
      return;
    }
    uni.setNavigationBarTitle({ title: '编辑角色' });
    loadRole();
  } else {
    if (!userStore.hasPermission('system.roles:create')) {
      uni.showToast({ title: '无权新建角色', icon: 'none' });
      setTimeout(goBack, 500);
      return;
    }
    uni.setNavigationBarTitle({ title: '新建角色' });
  }
});

async function loadRole() {
  loading.value = true;
  try {
    const role = await roleService.getRoleById(roleId.value);
    form.roleCode = role.roleCode;
    form.roleName = role.roleName;
    form.description = role.description || '';
    form.isActive = role.isActive;
  } catch (err) {
    uni.showToast({ title: err.message || '加载失败', icon: 'none' });
    setTimeout(goBack, 500);
  } finally {
    loading.value = false;
  }
}

async function submit() {
  const roleCode = form.roleCode.trim();
  const roleName = form.roleName.trim();
  const description = form.description.trim();

  if (!isEdit.value && !roleCode) {
    uni.showToast({ title: '请输入角色编码', icon: 'none' });
    return;
  }
  if (!roleName) {
    uni.showToast({ title: '请输入角色名称', icon: 'none' });
    return;
  }

  saving.value = true;
  try {
    if (isEdit.value) {
      await roleService.updateRole(roleId.value, {
        roleName,
        description: description || undefined,
        isActive: form.isActive
      });
    } else {
      await roleService.createRole({
        roleCode,
        roleName,
        description: description || undefined
      });
    }
    uni.showToast({ title: isEdit.value ? '更新成功' : '创建成功', icon: 'success' });
    setTimeout(goBack, 400);
  } catch (err) {
    uni.showToast({ title: err.message || '保存失败', icon: 'none' });
  } finally {
    saving.value = false;
  }
}

function goBack() {
  uni.navigateBack();
}
</script>

<style scoped lang="scss">
.actions {
  margin-top: 32rpx;
}
</style>

// frontend/src/app/pages/system/role-form.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzSpaceModule } from 'ng-zorro-antd/space';
import { NzSwitchModule } from 'ng-zorro-antd/switch';
import { finalize } from 'rxjs';
import { ApiBusinessError } from '../../core/models/api-result.model';
import { SysRoleService } from '../../service/sys-role.service';
import { PageHeaderComponent } from '../../shared/components/page-header/page-header.component';

@Component({
  selector: 'app-role-form',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    RouterLink,
    PageHeaderComponent,
    NzCardModule,
    NzFormModule,
    NzInputModule,
    NzButtonModule,
    NzSpaceModule,
    NzSwitchModule
  ],
  templateUrl: './role-form.component.html',
  styleUrl: './system-pages.scss'
})
export class RoleFormComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly roleService = inject(SysRoleService);
  private readonly message = inject(NzMessageService);
  private readonly fb = inject(FormBuilder);

  isEdit = false;
  roleId: number | null = null;
  loading = false;
  saving = false;

  form = this.fb.nonNullable.group({
    roleCode: ['', [Validators.required, Validators.maxLength(64)]],
    roleName: ['', [Validators.required, Validators.maxLength(64)]],
    description: [''],
    isActive: [true]
  });

  ngOnInit(): void {
    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {
      this.isEdit = true;
      this.roleId = Number(idParam);
      this.form.controls.roleCode.disable();
      this.loadRole(this.roleId);
    }
  }

  get pageTitle(): string {
    return this.isEdit ? '编辑角色' : '新建角色';
  }

  loadRole(id: number): void {
    this.loading = true;
    this.roleService.getRoleById(id).pipe(
      finalize(() => (this.loading = false))
    ).subscribe({
      next: role => {
        this.form.reset({
          roleCode: role.roleCode,
          roleName: role.roleName,
          description: role.description ?? '',
          isActive: role.isActive
        });
      },
      error: (err: unknown) => {
        this.message.error(err instanceof ApiBusinessError ? err.message : '加载失败');
        void this.router.navigate(['/system/roles']);
      }
    });
  }

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      this.message.warning('请完善必填项');
      return;
    }

    this.saving = true;
    const raw = this.form.getRawValue();
    const request$ = this.isEdit && this.roleId != null
      ? this.roleService.updateRole(this.roleId, {
          roleName: raw.roleName,
          description: raw.description,
          isActive: raw.isActive
        })
      : this.roleService.createRole({
          roleCode: raw.roleCode,
          roleName: raw.roleName,
          description: raw.description
        });

    request$.pipe(finalize(() => (this.saving = false))).subscribe({
      next: () => {
        this.message.success(this.isEdit ? '更新成功' : '创建成功');
        void this.router.navigate(['/system/roles']);
      },
      error: (err: unknown) => this.message.error(err instanceof ApiBusinessError ? err.message : '保存失败')
    });
  }
}

<div class="page-container">
  <app-page-header [title]="pageTitle" [subtitle]="isEdit ? '修改角色基本信息' : '填写角色基本信息'">
    <a routerLink="/system/roles">返回列表</a>
  </app-page-header>

  <nz-card class="page-card form-page-card" [nzLoading]="loading">
    <form nz-form [formGroup]="form" nzLayout="vertical" class="form-page">
      <div class="form-page-grid">
        <nz-form-item>
          <nz-form-label nzRequired>角色编码</nz-form-label>
          <nz-form-control nzErrorTip="请输入角色编码">
            <input nz-input formControlName="roleCode" placeholder="如 admin" [readonly]="isEdit" />
          </nz-form-control>
        </nz-form-item>
        <nz-form-item>
          <nz-form-label nzRequired>角色名称</nz-form-label>
          <nz-form-control nzErrorTip="请输入角色名称">
            <input nz-input formControlName="roleName" placeholder="如 管理员" />
          </nz-form-control>
        </nz-form-item>
        <nz-form-item class="form-page-full">
          <nz-form-label>描述</nz-form-label>
          <nz-form-control>
            <textarea nz-input formControlName="description" placeholder="可选" rows="3"></textarea>
          </nz-form-control>
        </nz-form-item>
        @if (isEdit) {
          <nz-form-item>
            <nz-form-label>启用</nz-form-label>
            <nz-form-control>
              <nz-switch formControlName="isActive"></nz-switch>
            </nz-form-control>
          </nz-form-item>
        }
      </div>

      <div class="form-page-actions">
        <nz-space>
          <button *nzSpaceItem nz-button nzType="primary" [nzLoading]="saving" (click)="submit()">保存</button>
          <a *nzSpaceItem nz-button routerLink="/system/roles">取消</a>
        </nz-space>
      </div>
    </form>
  </nz-card>
</div>
