// frontend/src/app/pages/system/user-form.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { NzAvatarModule } from 'ng-zorro-antd/avatar';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzMessageService } from 'ng-zorro-antd/message';
import { NzSpaceModule } from 'ng-zorro-antd/space';
import { NzSwitchModule } from 'ng-zorro-antd/switch';
import { NzUploadFile, NzUploadModule } from 'ng-zorro-antd/upload';
import { finalize } from 'rxjs';
import { ApiBusinessError } from '../../core/models/api-result.model';
import { FileService } from '../../service/file.service';
import { SysUserService } from '../../service/sys-user.service';
import { PageHeaderComponent } from '../../shared/components/page-header/page-header.component';
import { resolveAssetUrl } from '../../shared/utils/asset-url.util';
import { optionalEmailValidator } from '../../shared/utils/form.validators';

@Component({
  selector: 'app-user-form',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    RouterLink,
    PageHeaderComponent,
    NzCardModule,
    NzFormModule,
    NzInputModule,
    NzButtonModule,
    NzSpaceModule,
    NzSwitchModule,
    NzUploadModule,
    NzAvatarModule,
    NzIconModule
  ],
  templateUrl: './user-form.component.html',
  styleUrl: './system-pages.scss'
})
export class UserFormComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly userService = inject(SysUserService);
  private readonly fileService = inject(FileService);
  private readonly message = inject(NzMessageService);
  private readonly fb = inject(FormBuilder);

  isEdit = false;
  userId: number | null = null;
  loading = false;
  saving = false;
  uploadingAvatar = false;
  avatarUrl: string | undefined;
  avatarFileList: NzUploadFile[] = [];

  form = this.fb.nonNullable.group({
    userName: ['', [Validators.required, Validators.maxLength(64)]],
    password: [''],
    displayName: [''],
    email: ['', optionalEmailValidator],
    isActive: [true]
  });

  ngOnInit(): void {
    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {
      this.isEdit = true;
      this.userId = Number(idParam);
      this.form.controls.userName.disable();
      this.form.controls.password.setValidators([Validators.minLength(6)]);
      this.loadUser(this.userId);
    } else {
      this.form.controls.password.setValidators([Validators.required, Validators.minLength(6)]);
    }
  }

  get pageTitle(): string {
    return this.isEdit ? '编辑用户' : '新建用户';
  }

  loadUser(id: number): void {
    this.loading = true;
    this.userService.getUserById(id).pipe(
      finalize(() => (this.loading = false))
    ).subscribe({
      next: user => {
        if (!user) {
          this.message.error('用户不存在');
          void this.router.navigate(['/system/users']);
          return;
        }

        this.setAvatar(user.avatarUrl);
        this.form.reset({
          userName: user.userName,
          password: '',
          displayName: user.displayName ?? '',
          email: user.email ?? '',
          isActive: user.isActive
        });
      },
      error: (err: unknown) => {
        this.message.error(err instanceof ApiBusinessError ? err.message : '加载失败');
        void this.router.navigate(['/system/users']);
      }
    });
  }

  beforeAvatarUpload = (file: NzUploadFile): boolean => {
    const rawFile = (file.originFileObj ?? file) as File;
    if (!rawFile?.type?.startsWith('image/')) {
      this.message.error('只能上传图片文件');
      return false;
    }

    if (rawFile.size / 1024 / 1024 >= 2) {
      this.message.error('头像大小不能超过 2MB');
      return false;
    }

    this.uploadingAvatar = true;
    this.fileService.uploadAvatar(rawFile).pipe(
      finalize(() => (this.uploadingAvatar = false))
    ).subscribe({
      next: url => {
        this.setAvatar(url);
        this.message.success('头像上传成功');
      },
      error: (err: unknown) => this.message.error(err instanceof ApiBusinessError ? err.message : '头像上传失败')
    });

    return false;
  };

  removeAvatar = (): boolean => {
    this.avatarUrl = undefined;
    this.avatarFileList = [];
    return true;
  };

  submit(): void {
    this.form.controls.password.updateValueAndValidity();
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      this.message.warning('请完善必填项');
      return;
    }

    this.saving = true;
    const raw = this.form.getRawValue();
    const displayName = raw.displayName?.trim();
    const email = raw.email?.trim();
    const password = raw.password?.trim();

    const request$ = this.isEdit && this.userId != null
      ? this.userService.updateUser(this.userId, {
          displayName: displayName || undefined,
          email: email || undefined,
          isActive: raw.isActive,
          password: password || undefined,
          avatarUrl: this.avatarUrl
        })
      : this.userService.createUser({
          userName: raw.userName.trim(),
          password: raw.password,
          displayName: displayName || undefined,
          email: email || undefined,
          avatarUrl: this.avatarUrl
        });

    request$.pipe(finalize(() => (this.saving = false))).subscribe({
      next: () => {
        this.message.success(this.isEdit ? '更新成功' : '创建成功');
        void this.router.navigate(['/system/users']);
      },
      error: (err: unknown) => this.message.error(err instanceof ApiBusinessError ? err.message : '保存失败')
    });
  }

  private setAvatar(url?: string | null): void {
    this.avatarUrl = url || undefined;
    if (!url) {
      this.avatarFileList = [];
      return;
    }

    const displayUrl = resolveAssetUrl(url);
    this.avatarFileList = [{
      uid: '-1',
      name: 'avatar',
      status: 'done',
      url: displayUrl,
      thumbUrl: displayUrl
    }];
  }
}

<div class="page-container">
  <app-page-header [title]="pageTitle" [subtitle]="isEdit ? '修改用户基本信息' : '填写用户基本信息'">
    <a routerLink="/system/users">返回列表</a>
  </app-page-header>

  <nz-card class="page-card form-page-card" [nzLoading]="loading">
    <form nz-form [formGroup]="form" nzLayout="vertical" class="form-page">
      <div class="form-page-grid">
        <nz-form-item class="form-page-full avatar-upload-item">
          <nz-form-label>头像</nz-form-label>
          <nz-form-control>
            <nz-upload
              nzListType="picture-card"
              [nzShowUploadList]="{ showPreviewIcon: true, showRemoveIcon: true, showDownloadIcon: false }"
              [nzFileList]="avatarFileList"
              [nzBeforeUpload]="beforeAvatarUpload"
              [nzRemove]="removeAvatar"
              [nzAccept]="'image/*'"
              [nzDisabled]="uploadingAvatar">
              @if (avatarFileList.length === 0) {
                <div class="avatar-upload-trigger">
                  <span nz-icon [nzType]="uploadingAvatar ? 'loading' : 'plus'"></span>
                  <div class="avatar-upload-text">上传头像</div>
                </div>
              }
            </nz-upload>
            <div class="form-hint">支持 JPG、PNG、GIF、WEBP，大小不超过 2MB</div>
          </nz-form-control>
        </nz-form-item>

        <nz-form-item>
          <nz-form-label nzRequired>用户名</nz-form-label>
          <nz-form-control nzErrorTip="请输入用户名">
            <input nz-input formControlName="userName" placeholder="请输入用户名" [readonly]="isEdit" />
          </nz-form-control>
        </nz-form-item>
        <nz-form-item>
          <nz-form-label [nzRequired]="!isEdit">密码</nz-form-label>
          <nz-form-control nzErrorTip="密码至少 6 位">
            <input
              nz-input
              type="password"
              formControlName="password"
              [placeholder]="isEdit ? '留空则不修改' : '请输入密码'" />
          </nz-form-control>
        </nz-form-item>
        <nz-form-item>
          <nz-form-label>显示名</nz-form-label>
          <nz-form-control>
            <input nz-input formControlName="displayName" placeholder="可选" />
          </nz-form-control>
        </nz-form-item>
        <nz-form-item>
          <nz-form-label>邮箱</nz-form-label>
          <nz-form-control nzErrorTip="邮箱格式不正确">
            <input nz-input formControlName="email" placeholder="可选" />
          </nz-form-control>
        </nz-form-item>
        @if (isEdit) {
          <nz-form-item>
            <nz-form-label>启用</nz-form-label>
            <nz-form-control>
              <nz-switch formControlName="isActive"></nz-switch>
            </nz-form-control>
          </nz-form-item>
        }
      </div>

      <div class="form-page-actions">
        <nz-space>
          <button *nzSpaceItem nz-button nzType="primary" [nzLoading]="saving" (click)="submit()">保存</button>
          <a *nzSpaceItem nz-button routerLink="/system/users">取消</a>
        </nz-space>
      </div>
    </form>
  </nz-card>
</div>

// mobile/pages/system/user-form/user-form.vue
<template>
  <view class="page page-container">
    <u-loading-page :loading="loading" loading-text="加载中..." />

    <view v-if="!loading" class="card">
      <view class="avatar-section" @click="chooseAvatar">
        <u-avatar :src="avatarPreview" :text="avatarText" size="72" bg-color="#1677ff" />
        <text class="avatar-section__tip muted">{{ uploadingAvatar ? '上传中...' : '点击上传头像' }}</text>
      </view>

      <u-form label-position="top">
        <u-form-item label="用户名" required>
          <u-input
            v-model="form.userName"
            placeholder="请输入用户名"
            :disabled="isEdit"
            clearable />
        </u-form-item>
        <u-form-item :label="isEdit ? '密码' : '密码'" :required="!isEdit">
          <u-input
            v-model="form.password"
            type="password"
            :placeholder="isEdit ? '留空则不修改' : '至少 6 位'"
            clearable />
        </u-form-item>
        <u-form-item label="显示名">
          <u-input v-model="form.displayName" placeholder="可选" clearable />
        </u-form-item>
        <u-form-item label="邮箱">
          <u-input v-model="form.email" placeholder="可选" clearable />
        </u-form-item>
        <u-form-item v-if="isEdit" label="启用">
          <u-switch v-model="form.isActive" />
        </u-form-item>
      </u-form>
    </view>

    <view class="actions">
      <u-button type="primary" :loading="saving" text="保存" @click="submit" />
      <u-button text="取消" custom-style="margin-top: 20rpx;" @click="goBack" />
    </view>
  </view>
</template>

<script setup>
import { computed, reactive, ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import * as userService from '@/service/user.service';
import { useUserStore } from '@/store/user';
import { resolveAssetUrl } from '@/utils/format';

const userStore = useUserStore();

const isEdit = ref(false);
const userId = ref(null);
const loading = ref(false);
const saving = ref(false);
const uploadingAvatar = ref(false);
const avatarUrl = ref('');

const form = reactive({
  userName: '',
  password: '',
  displayName: '',
  email: '',
  isActive: true
});

const avatarPreview = computed(() => resolveAssetUrl(avatarUrl.value));
const avatarText = computed(() => (form.userName || 'U').slice(0, 1).toUpperCase());

onLoad(options => {
  if (!userStore.isLoggedIn) {
    uni.reLaunch({ url: '/pages/login/login' });
    return;
  }

  if (options.id) {
    isEdit.value = true;
    userId.value = Number(options.id);
    if (!userStore.hasPermission('system.users:edit')) {
      uni.showToast({ title: '无权编辑用户', icon: 'none' });
      setTimeout(goBack, 500);
      return;
    }
    uni.setNavigationBarTitle({ title: '编辑用户' });
    loadUser();
  } else {
    if (!userStore.hasPermission('system.users:create')) {
      uni.showToast({ title: '无权新建用户', icon: 'none' });
      setTimeout(goBack, 500);
      return;
    }
    uni.setNavigationBarTitle({ title: '新建用户' });
  }
});

async function loadUser() {
  loading.value = true;
  try {
    const user = await userService.getUserById(userId.value);
    form.userName = user.userName;
    form.displayName = user.displayName || '';
    form.email = user.email || '';
    form.isActive = user.isActive;
    form.password = '';
    avatarUrl.value = user.avatarUrl || '';
  } catch (err) {
    uni.showToast({ title: err.message || '加载失败', icon: 'none' });
    setTimeout(goBack, 500);
  } finally {
    loading.value = false;
  }
}

function chooseAvatar() {
  uni.chooseImage({
    count: 1,
    sizeType: ['compressed'],
    success: async res => {
      const filePath = res.tempFilePaths[0];
      uploadingAvatar.value = true;
      try {
        avatarUrl.value = await userService.uploadAvatar(filePath);
        uni.showToast({ title: '头像上传成功', icon: 'success' });
      } catch (err) {
        uni.showToast({ title: err.message || '头像上传失败', icon: 'none' });
      } finally {
        uploadingAvatar.value = false;
      }
    }
  });
}

async function submit() {
  const userName = form.userName.trim();
  const password = form.password.trim();
  const displayName = form.displayName.trim();
  const email = form.email.trim();

  if (!isEdit.value && !userName) {
    uni.showToast({ title: '请输入用户名', icon: 'none' });
    return;
  }
  if (!isEdit.value && password.length < 6) {
    uni.showToast({ title: '密码至少 6 位', icon: 'none' });
    return;
  }
  if (isEdit.value && password && password.length < 6) {
    uni.showToast({ title: '密码至少 6 位', icon: 'none' });
    return;
  }

  saving.value = true;
  try {
    if (isEdit.value) {
      await userService.updateUser(userId.value, {
        displayName: displayName || undefined,
        email: email || undefined,
        isActive: form.isActive,
        password: password || undefined,
        avatarUrl: avatarUrl.value || undefined
      });
    } else {
      await userService.createUser({
        userName,
        password,
        displayName: displayName || undefined,
        email: email || undefined,
        avatarUrl: avatarUrl.value || undefined
      });
    }
    uni.showToast({ title: isEdit.value ? '更新成功' : '创建成功', icon: 'success' });
    setTimeout(goBack, 400);
  } catch (err) {
    uni.showToast({ title: err.message || '保存失败', icon: 'none' });
  } finally {
    saving.value = false;
  }
}

function goBack() {
  uni.navigateBack();
}
</script>

<style scoped lang="scss">
.avatar-section {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 16rpx 0 32rpx;

  &__tip {
    margin-top: 16rpx;
    font-size: 24rpx;
  }
}

.actions {
  margin-top: 32rpx;
}
</style>
